#version 460 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (rgba32f, binding = 0) uniform image2D img_output;

void main() {
    ivec2 tex_coord = ivec2(gl_GlobalInvocationID.xy);
    vec4 value = vec4(float(tex_coord.x) / (gl_NumWorkGroups.x), 
                      float(tex_coord.y) / (gl_NumWorkGroups.y), 
                      0.0, 1.0);
    imageStore(img_output, tex_coord, value);
}
