#version 460

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D img_out;

void main() {
    vec4 pixel_color =
        vec4(float(gl_GlobalInvocationID.x) / float(gl_NumWorkGroups.x - 1),
            float(gl_GlobalInvocationID.y) / float(gl_NumWorkGroups.y - 1),
            0.25, 1.0);
    ivec2 pixel_coord = ivec2(gl_GlobalInvocationID.xy);
    imageStore(img_out, pixel_coord, pixel_color);
}
