#version 460

#extension GL_EXT_scalar_block_layout: require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

// rounded up to power of 2
layout(constant_id = 0) const uint GRID_SPHERE_PAIR_ROUNDED_UP_COUNT = 1;

layout(std430, binding = 1) writeonly buffer intersection_pair {
    uint intersection_grid_id[GRID_SPHERE_PAIR_ROUNDED_UP_COUNT];
    uint intersection_sphere_id[GRID_SPHERE_PAIR_ROUNDED_UP_COUNT];
};

void main() {
}

